import java.text.DateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.ResourceBundle;

public class odeon extends javax.swing.JFrame {

    public DateFormat formatter;
    public static String today;
    Locale [] locales = {new Locale("en","ie"), new Locale("sk","sk"), new Locale("es","es")};
    public static Locale selLocale;
    public static ResourceBundle rb = ResourceBundle.getBundle("bundles/English", new Locale("en","ie"));
    
    /** Creates new form odeon */
    public odeon() {
        initComponents();
        setLocationRelativeTo(null);
        
        updateLabels(rb);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoLeft = new javax.swing.JLabel();
        lblLogoRight = new javax.swing.JLabel();
        pnlFlag = new javax.swing.JPanel();
        irishBtn = new javax.swing.JButton();
        slovakBtn = new javax.swing.JButton();
        spanishBtn = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();

        setTitle("Odeon Cineplex");
        setResizable(false);

        lblLogoLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.jpg"))); // NOI18N

        lblLogoRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.jpg"))); // NOI18N

        irishBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/irish.jpg"))); // NOI18N
        irishBtn.setToolTipText("IE");
        irishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irishBtnActionPerformed(evt);
            }
        });

        slovakBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/slovak.jpg"))); // NOI18N
        slovakBtn.setToolTipText("SK");
        slovakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slovakBtnActionPerformed(evt);
            }
        });

        spanishBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spanish.jpg"))); // NOI18N
        spanishBtn.setToolTipText("ES");
        spanishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spanishBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFlagLayout = new javax.swing.GroupLayout(pnlFlag);
        pnlFlag.setLayout(pnlFlagLayout);
        pnlFlagLayout.setHorizontalGroup(
            pnlFlagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(irishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(slovakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(spanishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        pnlFlagLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {irishBtn, slovakBtn, spanishBtn});

        pnlFlagLayout.setVerticalGroup(
            pnlFlagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFlagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slovakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(spanishBtn, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(irishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlFlagLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {irishBtn, slovakBtn, spanishBtn});

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to ODEON CINEPLEX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogoLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                        .addComponent(lblLogoRight)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogoRight)
                    .addComponent(lblLogoLeft))
                .addGap(83, 83, 83)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(pnlFlag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irishBtnActionPerformed
        setMyLocale("ie");
        selLocale = new Locale("en","ie");
        rb = ResourceBundle.getBundle("bundles/English", selLocale);
        new option().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_irishBtnActionPerformed

    private void slovakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slovakBtnActionPerformed
        setMyLocale("sk");
        selLocale = new Locale("sk","sk");
        rb = ResourceBundle.getBundle("bundles/Slovak", selLocale);
        new option().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_slovakBtnActionPerformed

    private void spanishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spanishBtnActionPerformed
        setMyLocale("es");
        selLocale = new Locale("es","es");
        rb = ResourceBundle.getBundle("bundles/Spanish", selLocale);
        new option().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_spanishBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odeon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irishBtn;
    private javax.swing.JLabel lblLogoLeft;
    private javax.swing.JLabel lblLogoRight;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlFlag;
    private javax.swing.JButton slovakBtn;
    private javax.swing.JButton spanishBtn;
    // End of variables declaration//GEN-END:variables

    
    private void setMyLocale(String country) {
        GregorianCalendar cal = new GregorianCalendar();

        if(country.equals("ie")){
            formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, locales[0]);
        }
        else if(country.equals("sk")){
            formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, locales[1]);
        }
        else{
            formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, locales[2]);
        }

        today = formatter.format(cal.getTime());
    }
    
    public void updateLabels(ResourceBundle rb){
        lblWelcome.setText(rb.getString("ODEON CINEPLEX"));
    }
    
}
