import java.awt.Color;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import java.text.NumberFormat;


public class payment extends javax.swing.JFrame {

    /** Creates new form payment */
    public payment() {
        initComponents();
        setLocationRelativeTo(this);
        updateLabels(odeon.rb);

        lblTotalAmount.setText(Double.toString(sale.myTicket.getTicketPrice()));

        lblDateTime.setText(odeon.today);

        NumberFormat currency = NumberFormat.getCurrencyInstance(odeon.selLocale);
        btnEuro10.setText(currency.format(10));
        btnEuro20.setText(currency.format(20));
        btnEuro50.setText(currency.format(50));
        btnEuro100.setText(currency.format(100));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTotalDue = new javax.swing.JLabel();
        pnlPaymentOption = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnEuro10 = new javax.swing.JButton();
        btnEuro20 = new javax.swing.JButton();
        btnEuro50 = new javax.swing.JButton();
        btnEuro100 = new javax.swing.JButton();
        txtFldCashGiven = new javax.swing.JTextField();
        lblCashGiven = new javax.swing.JLabel();
        btnCalculateChange = new javax.swing.JButton();
        lblTotalAmount = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();

        setTitle("Payment for Tickets");
        setResizable(false);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setText("Date:");

        lblTotalDue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalDue.setText("Total Due:");

        pnlPaymentOption.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amount Tendered", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnEuro10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEuro10.setText("€ 10");
        btnEuro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEuro10ActionPerformed(evt);
            }
        });

        btnEuro20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEuro20.setText("€ 20");
        btnEuro20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEuro20ActionPerformed(evt);
            }
        });

        btnEuro50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEuro50.setText("€ 50");
        btnEuro50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEuro50ActionPerformed(evt);
            }
        });

        btnEuro100.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEuro100.setText("€ 100");
        btnEuro100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEuro100ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnEuro10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnEuro20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnEuro50, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnEuro100, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEuro10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addComponent(btnEuro20, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addComponent(btnEuro50, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
            .addComponent(btnEuro100, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        txtFldCashGiven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFldCashGiven.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldCashGiven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCashGivenActionPerformed(evt);
            }
        });

        lblCashGiven.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblCashGiven.setText("Cash Given:");

        btnCalculateChange.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalculateChange.setText("Compute Change & Print Tickets");
        btnCalculateChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentOptionLayout = new javax.swing.GroupLayout(pnlPaymentOption);
        pnlPaymentOption.setLayout(pnlPaymentOptionLayout);
        pnlPaymentOptionLayout.setHorizontalGroup(
            pnlPaymentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaymentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPaymentOptionLayout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(pnlPaymentOptionLayout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(btnCalculateChange, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentOptionLayout.createSequentialGroup()
                        .addComponent(lblCashGiven)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldCashGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))))
        );
        pnlPaymentOptionLayout.setVerticalGroup(
            pnlPaymentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnlPaymentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashGiven)
                    .addComponent(txtFldCashGiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnCalculateChange, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPaymentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalDue)
                        .addGap(27, 27, 27)
                        .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDue)
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(pnlPaymentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblDateTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldCashGivenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCashGivenActionPerformed

        try {
            double amountGiven = Double.parseDouble(txtFldCashGiven.getText());
            checkAmountGiven(amountGiven);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, odeon.rb.getString("ERROR ENTER VALUE") + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_txtFldCashGivenActionPerformed

    private void btnEuro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEuro10ActionPerformed
        txtFldCashGiven.setText("10");
        checkAmountGiven(10);
    }//GEN-LAST:event_btnEuro10ActionPerformed

    private void btnEuro20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEuro20ActionPerformed
        txtFldCashGiven.setText("20");
        checkAmountGiven(20);
    }//GEN-LAST:event_btnEuro20ActionPerformed

    private void btnEuro50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEuro50ActionPerformed
        txtFldCashGiven.setText("50");
        checkAmountGiven(50);
    }//GEN-LAST:event_btnEuro50ActionPerformed

    private void btnEuro100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEuro100ActionPerformed
        txtFldCashGiven.setText("100");
        checkAmountGiven(100);
    }//GEN-LAST:event_btnEuro100ActionPerformed

    private void btnCalculateChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateChangeActionPerformed
        try {
            double amount = Double.parseDouble(txtFldCashGiven.getText());
            if (checkAmountGiven(amount)) {
                sale.myTicket.setAmountTender(amount);

                new ticket().setVisible(true);
                this.setVisible(false);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, odeon.rb.getString("ERROR ENTER VALUE") + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnCalculateChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateChange;
    private javax.swing.JButton btnEuro10;
    private javax.swing.JButton btnEuro100;
    private javax.swing.JButton btnEuro20;
    private javax.swing.JButton btnEuro50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCashGiven;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JPanel pnlPaymentOption;
    private javax.swing.JTextField txtFldCashGiven;
    // End of variables declaration//GEN-END:variables

    public boolean checkAmountGiven(double amount) {
        if (amount < sale.myTicket.getTicketPrice()) {
            txtFldCashGiven.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, odeon.rb.getString("ERROR HIGHER VALUE")+ "  " + amount);
            return false;
        } else {
            txtFldCashGiven.setForeground(Color.black);
            return true;
        }
    }

    public void updateLabels(ResourceBundle rb) {
        lblDate.setText(rb.getString("DATE"));

        lblTotalDue.setText(rb.getString("TOTAL DUE"));
        lblCashGiven.setText(rb.getString("CASH GIVEN"));
        btnCalculateChange.setText("COMPUTE CHANGE");


    }
}
