
import java.text.DecimalFormat;
import java.util.ResourceBundle;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ticket.java
 *
 * Created on 19-Oct-2011, 13:36:02
 */


public class ticket extends javax.swing.JFrame {

    /** Creates new form ticket */
    public ticket() {
        initComponents();
        setLocationRelativeTo(this);
        
        updateLabels(odeon.rb);
        
        DecimalFormat twoDigits = new DecimalFormat("0.00");
        
        int row[] = sale.myTicket.getRow();
        int seat[] = sale.myTicket.getSeat();
        
        Movie m = (Movie) admin.movies.get(sale.myTicket.getMovieId());
        
        lblDateTime.setText(odeon.today);
        lblMovie.setText(m.getTitle());
        lblScreenNum.setText(Integer.toString(m.getScreen()));
        lblTimeNum.setText(sale.myTicket.getShowTime());
        lblPaxAmount.setText(Integer.toString(sale.myTicket.getNumTickets()));
        lblAmountDue.setText(Double.toString(sale.myTicket.getTicketPrice()));
        lblTotalAmountDue.setText(Double.toString(sale.myTicket.getTicketPrice()));
        
        lblAmountTenderedNum.setText(Double.toString(sale.myTicket.getAmountTender()));
        double change = sale.myTicket.getAmountTender() - sale.myTicket.getTicketPrice();
        String change2d = twoDigits.format(change);        
        lblChangeDueNum.setText(change2d);
        
        String output = "";
        
        for(int i=0; i<row.length; i++){
                       
            output += odeon.rb.getString("ROW")+ "  " + row[i] + "  " + odeon.rb.getString("SEAT")+ "  " + seat[i] + "\n";
        }
        
        txtAreaSeats.setText(output);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHorRuleCinTitle = new javax.swing.JLabel();
        lblCinemaTitle = new javax.swing.JLabel();
        lblShowing = new javax.swing.JLabel();
        lblAmountDue = new javax.swing.JLabel();
        lblAdmit = new javax.swing.JLabel();
        lblAmountTendered = new javax.swing.JLabel();
        lblChangeDue = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblTotalAmountDue = new javax.swing.JLabel();
        lblAmountTenderedNum = new javax.swing.JLabel();
        lblChangeDueNum = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHorRuleAmount = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        lblMovie = new javax.swing.JLabel();
        lblScreen = new javax.swing.JLabel();
        lblScreenNum = new javax.swing.JLabel();
        lblTimeNum = new javax.swing.JLabel();
        btnBackToSales = new javax.swing.JButton();
        lblPaxAmount = new javax.swing.JLabel();
        lblPax = new javax.swing.JLabel();
        pnlSeats = new javax.swing.JPanel();
        lblSeatsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSeats = new javax.swing.JTextArea();

        setTitle("Print Tickets");
        setResizable(false);

        lblHorRuleCinTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHorRuleCinTitle.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        lblCinemaTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCinemaTitle.setText("ODEON CINEPLEX - Limerick");

        lblShowing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblShowing.setText("Showing");

        lblAmountDue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmountDue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblAdmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdmit.setText("Admit");

        lblAmountTendered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmountTendered.setText("Amount Tendered");

        lblChangeDue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblChangeDue.setText("Change Due");

        lblGreetings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGreetings.setText("Enjoy The Movie");

        lblTotalAmountDue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmountDue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblAmountTenderedNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmountTenderedNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblChangeDueNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblChangeDueNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setText("Date:");

        lblHorRuleAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHorRuleAmount.setText("- - - - - - - - - - - - - - - - - - ");

        lblMovie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblScreen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblScreen.setText("Screen ");

        lblScreenNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblTimeNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBackToSales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBackToSales.setText("Sales");
        btnBackToSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToSalesActionPerformed(evt);
            }
        });

        lblPaxAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblPax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPax.setText("pax");

        lblSeatsTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSeatsTitle.setText("Seats");

        txtAreaSeats.setEditable(false);
        txtAreaSeats.setColumns(20);
        txtAreaSeats.setRows(5);
        jScrollPane1.setViewportView(txtAreaSeats);

        javax.swing.GroupLayout pnlSeatsLayout = new javax.swing.GroupLayout(pnlSeats);
        pnlSeats.setLayout(pnlSeatsLayout);
        pnlSeatsLayout.setHorizontalGroup(
            pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeatsTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSeatsLayout.setVerticalGroup(
            pnlSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeatsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblShowing)
                                .addGap(18, 18, 18)
                                .addComponent(lblMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScreen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblScreenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTimeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(lblHorRuleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAmountTenderedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblChangeDue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblChangeDueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pnlSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdmit)
                                .addGap(18, 18, 18)
                                .addComponent(lblPaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGreetings)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPax)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblAmountTendered)
                            .addComponent(lblCinemaTitle)
                            .addComponent(lblHorRuleCinTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addGap(18, 18, 18)
                                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBackToSales)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblTotalAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackToSales))
                .addGap(29, 29, 29)
                .addComponent(lblCinemaTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorRuleCinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowing)
                    .addComponent(lblMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScreen)
                    .addComponent(lblScreenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAdmit)
                        .addComponent(lblPaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPax))
                    .addComponent(lblAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblHorRuleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmountTendered)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChangeDue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChangeDueNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addComponent(lblGreetings))
                    .addComponent(lblAmountTenderedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToSalesActionPerformed
        new sale().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToSalesActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToSales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmit;
    private javax.swing.JLabel lblAmountDue;
    private javax.swing.JLabel lblAmountTendered;
    private javax.swing.JLabel lblAmountTenderedNum;
    private javax.swing.JLabel lblChangeDue;
    private javax.swing.JLabel lblChangeDueNum;
    private javax.swing.JLabel lblCinemaTitle;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblHorRuleAmount;
    private javax.swing.JLabel lblHorRuleCinTitle;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblPax;
    private javax.swing.JLabel lblPaxAmount;
    private javax.swing.JLabel lblScreen;
    private javax.swing.JLabel lblScreenNum;
    private javax.swing.JLabel lblSeatsTitle;
    private javax.swing.JLabel lblShowing;
    private javax.swing.JLabel lblTimeNum;
    private javax.swing.JLabel lblTotalAmountDue;
    private javax.swing.JPanel pnlSeats;
    private javax.swing.JTextArea txtAreaSeats;
    // End of variables declaration//GEN-END:variables

    public void updateLabels(ResourceBundle rb){
        lblDate.setText(rb.getString("DATE"));
        
        lblShowing.setText(rb.getString("SHOWING"));
        lblScreen.setText(rb.getString("SCREEN"));
        lblAdmit.setText(rb.getString("ADMIT"));
        lblPax.setText(rb.getString("PAX"));
        lblAmountTendered.setText(rb.getString("AMOUNT TENDERED"));
        lblChangeDue.setText(rb.getString("CHANGE DUE"));                
        lblGreetings.setText(rb.getString("GREETING"));
        lblSeatsTitle.setText(rb.getString("SEATS"));
        btnBackToSales.setText(rb.getString("SALES"));
        
    }
    
}
